/* Design system: light editorial exam platform; ink blue #174A72, warm paper #F7F4ED, royal blue actions, no fixed sidebar overlap. */
import { useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import {
  ArrowLeft, ArrowUpLeft, BookOpenCheck, CalendarDays, Check,
  ChevronDown, Clock3, FilePlus2, GraduationCap, LayoutDashboard,
  ListChecks, Menu, MessageCircle, PenLine, Play, Search, Settings2,
  Sparkles, Target, Trophy, Users, X, Zap,
} from "lucide-react";

const nav = [
  { href: "/", label: "الرئيسية", icon: LayoutDashboard },
  { href: "/my-quizzes", label: "اختباراتي", icon: ListChecks },
  { href: "/practice", label: "التدريب الحر", icon: PenLine },
  { href: "/daily", label: "سؤال اليوم", icon: CalendarDays },
  { href: "/mistakes", label: "بنك الأخطاء", icon: Target },
  { href: "/history", label: "السجل", icon: Clock3 },
  { href: "/classes", label: "الفصول", icon: Users },
  { href: "/community", label: "المجتمع", icon: MessageCircle },
  { href: "/leaderboard", label: "لوحة الصدارة", icon: Trophy },
];

function Brand() {
  return <Link href="/" className="brand"><span className="brand-mark-fallback" aria-hidden="true">M<span>✓</span></span><span><b>Musical Fishstick</b><small>منصة الاختبارات والتعلّم</small></span></Link>;
}

function Shell({ children }: { children: React.ReactNode }) {
  const [location] = useLocation();
  const [open, setOpen] = useState(false);
  return <div className="app-shell">
    <header className="topbar">
      <div className="topbar-inner">
        <button className="icon-button mobile-menu" aria-label="فتح القائمة" onClick={() => setOpen(true)}><Menu size={21} /></button>
        <Brand />
        <nav className="desktop-nav" aria-label="التنقل الرئيسي">{nav.slice(0, 5).map(({ href, label }) => <Link key={href} href={href} className={location === href ? "active" : ""}>{label}</Link>)}</nav>
        <div className="top-actions"><Link className="search-link" href="/practice"><Search size={18} /><span>ابحث في بنك الأسئلة</span></Link><Link className="profile" href="/login"><span>زائر</span><i>ز</i></Link></div>
      </div>
    </header>
    {open && <div className="drawer-backdrop" onClick={() => setOpen(false)}><aside className="mobile-drawer" onClick={e => e.stopPropagation()}><div className="drawer-head"><Brand /><button className="icon-button" aria-label="إغلاق" onClick={() => setOpen(false)}><X size={19} /></button></div><nav>{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={location === href ? "active" : ""} onClick={() => setOpen(false)}><Icon size={17} />{label}</Link>)}</nav><Link className="drawer-login" href="/login">تسجيل الدخول <ArrowLeft size={16} /></Link></aside></div>}
    <main className="main-wrap">{children}</main>
    <footer className="site-footer"><span>Musical Fishstick</span><span>تعلم بوضوح، واختبر بثقة.</span><Link href="/community">المجتمع</Link><Link href="/login">تسجيل الدخول</Link></footer>
  </div>;
}

function PageTitle({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function Button({ children, href, secondary = false }: { children: React.ReactNode; href?: string; secondary?: boolean }) { const className = secondary ? "btn secondary" : "btn"; return href ? <Link href={href} className={className}>{children}</Link> : <button className={className}>{children}</button>; }
function Stat({ icon: Icon, value, label, tone }: { icon: typeof Zap; value: string; label: string; tone: string }) { return <div className="stat"><span className={`stat-icon ${tone}`}><Icon size={17} /></span><div><b>{value}</b><small>{label}</small></div></div>; }
function Empty({ title, text, href, action }: { title: string; text: string; href?: string; action?: string }) { return <div className="empty"><div className="empty-mark"><BookOpenCheck size={23} /></div><b>{title}</b><p>{text}</p>{href && <Link href={href} className="text-link">{action || "اذهب الآن"} <ArrowLeft size={14} /></Link>}</div>; }

function Dashboard() {
  return <><PageTitle eyebrow="لوحة التحكم" title="أهلاً بك في ملتقى الطلاب" description="كل أدوات الاختبار والتدريب والتقدم في مكان واحد." action={<Button href="/quiz-create"><FilePlus2 size={17} /> إنشاء اختبار</Button>} />
    <section className="hero-paper"><div className="hero-copy"><span className="hero-label">جاهز لجولة جديدة؟</span><h2>اختبر فهمك، ثم اعرف أين تحتاج إلى مراجعة.</h2><p>أنشئ اختبارًا تنافسيًا أو ابدأ جولة تدريب قصيرة واحصل على تقدم واضح.</p><div className="hero-actions"><Button href="/practice">ابدأ التدريب <ArrowLeft size={16} /></Button><Button href="/quiz-create" secondary>أنشئ اختبارًا</Button></div></div><div className="hero-image"><div className="paper-lines" aria-label="ورقة اختبار مرتبة"><span>01</span><span>02</span><span>03</span><b>✓</b></div></div></section>
    <div className="stats-grid"><Stat icon={Zap} value="—" label="نقاط التقدم" tone="blue" /><Stat icon={CalendarDays} value="—" label="سلسلة الأيام" tone="yellow" /><Stat icon={Check} value="—" label="اختبارات مكتملة" tone="green" /><Stat icon={Trophy} value="—" label="ترتيبك الحالي" tone="red" /></div>
    <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">مسارك</span><h2>آخر النشاط</h2></div><Link href="/history" className="text-link">عرض السجل <ArrowLeft size={14} /></Link></div><Empty title="سجّل دخولك لتشاهد تقدمك" text="احفظ نتائجك ونقاطك وبنك أخطائك مع حسابك." href="/login" action="تسجيل الدخول" /></section><section className="panel quick-panel"><div className="panel-head"><div><span className="eyebrow">وصول سريع</span><h2>ماذا تريد أن تفعل؟</h2></div></div><div className="quick-grid"><Link href="/daily" className="quick"><CalendarDays size={19} /><b>سؤال اليوم</b><small>حافظ على عادتك</small></Link><Link href="/practice" className="quick"><PenLine size={19} /><b>تدريب حر</b><small>تدرّب بلا وقت</small></Link><Link href="/leaderboard" className="quick"><Trophy size={19} /><b>الصدارة</b><small>شاهد ترتيبك</small></Link><Link href="/classes" className="quick"><Users size={19} /><b>فصولي</b><small>تعلّم مع مجموعتك</small></Link></div></section></div>
    <section className="panel weekly"><div className="panel-head"><div><span className="eyebrow">استمرارية التعلم</span><h2>تقدمك هذا الأسبوع</h2></div><span className="muted">هدفك: 5 جلسات</span></div><div className="progress-label"><span>0 من 5 جلسات</span><span>0%</span></div><div className="progress"><i /></div><div className="days"><span>السبت</span><span>الأحد</span><span>الاثنين</span><span>الثلاثاء</span><span>الأربعاء</span><span>الخميس</span><span>الجمعة</span></div></section>
  </>;
}

function QuizCreate() { return <><PageTitle eyebrow="اختبار جديد" title="أنشئ اختبارًا يليق بطلابك" description="حدد الإعدادات، ثم شارك رابط الاختبار مع المتنافسين." /><div className="form-layout"><section className="panel form-card"><div className="form-note"><Sparkles size={18} /><span>يتم اختيار الأسئلة عشوائيًا من بنك الأسئلة.</span></div><label>عنوان الاختبار<input placeholder="مثال: مراجعة الوحدة الأولى" /></label><div className="two-col"><label>المدة بالدقائق<input type="number" defaultValue="10" /></label><label>عدد الأسئلة<input type="number" defaultValue="5" /></label></div><label>فئة الأسئلة<select><option>كل الأسئلة</option><option>رياضيات</option><option>علوم</option></select></label><div className="form-actions"><Button>إنشاء الاختبار <ArrowLeft size={16} /></Button><Button href="/" secondary>إلغاء</Button></div></section><aside className="side-note"><span className="number">01</span><h3>اختبار واضح يبدأ من إعداد واضح.</h3><p>استخدم عنوانًا يشرح الهدف، واختر عددًا مناسبًا من الأسئلة حتى يحافظ الاختبار على إيقاعه.</p></aside></div></>; }
function Practice() { return <><PageTitle eyebrow="التدريب" title="تدرّب على مهلك" description="جولة قصيرة تساعدك على تثبيت المعلومة قبل الاختبار." /><div className="practice-layout"><section className="panel practice-card"><div className="practice-art"><div className="paper-lines study-lines" aria-label="دفتر تدريب"><span>سؤال 01</span><span>سؤال 02</span><span>سؤال 03</span><b>✓</b></div></div><div className="practice-copy"><span className="eyebrow">جلسة جديدة</span><h2>اختر عدد الأسئلة وابدأ.</h2><p>لا يوجد مؤقت ولا درجة نهائية. كل إجابة فرصة لتعرف ما تحتاج إلى مراجعته.</p><div className="two-col"><label>الفئة<select><option>كل الأسئلة</option></select></label><label>عدد الأسئلة<input type="number" defaultValue="10" /></label></div><Button>ابدأ التدريب <Play size={16} fill="currentColor" /></Button></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">إحصاء بسيط</span><h2>هدف الجلسة</h2></div></div><div className="goal"><div className="goal-ring">10</div><div><b>أسئلة جديدة</b><p>ابدأ بخطوة صغيرة، واستمر يومًا بعد يوم.</p></div></div></section></div></>; }
function Daily() { return <><PageTitle eyebrow="كل يوم سؤال" title="سؤال اليوم" description="سؤال واحد، فكرة واحدة جديدة، وتقدم يتراكم مع الوقت." /><section className="daily-layout"><div className="daily-question"><span className="question-number">سؤال 01</span><h2>ما الفكرة التي تريد أن تثبتها اليوم؟</h2><p className="muted">سيظهر سؤال اليوم هنا عند توفر بنك الأسئلة.</p><div className="answers"><button><i>أ</i>الإجابة الأولى</button><button><i>ب</i>الإجابة الثانية</button><button><i>ج</i>الإجابة الثالثة</button><button><i>د</i>الإجابة الرابعة</button></div><Button>تأكيد الإجابة <Check size={16} /></Button></div><div className="daily-image"><div className="paper-lines result-lines" aria-label="ورقة إجابة"><span>الإجابة</span><span>التقدم</span><span>المراجعة</span><b>✓</b></div></div></section></>; }
function Leaderboard() { const rows = [{name:"Test Reviewer", points:"0"},{name:"كرم",points:"0"}]; return <><PageTitle eyebrow="منافسة ودية" title="لوحة الصدارة" description="تابع تقدمك بين الطلاب، واحتفل بكل خطوة إلى الأمام." /><section className="panel leaderboard"><div className="filter-row"><div className="search-field"><Search size={17} /><input placeholder="فلترة حسب الصف أو السنة" /></div><Button>فلترة</Button></div><div className="table-head"><span>الترتيب</span><span>الطالب</span><span>النقاط</span></div>{rows.map((r,i)=><div className="rank-row" key={r.name}><strong>0{i+1}</strong><span className="rank-name"><i>{r.name[0]}</i>{r.name}</span><b>{r.points} نقطة</b></div>)}</section></>; }
function SimplePage({ kind }: { kind: string }) { const data: Record<string,{eyebrow:string;title:string;description:string;text:string;href:string;action:string}> = {"my-quizzes":{eyebrow:"إدارة الاختبارات",title:"اختباراتي",description:"كل الاختبارات التي أنشأتها في مكان واحد.",text:"سجّل دخولك حتى تحفظ اختباراتك وتتابع نتائج المشاركين.",href:"/login",action:"تسجيل الدخول"},mistakes:{eyebrow:"مراجعة ذكية",title:"بنك الأخطاء",description:"ارجع إلى الأسئلة التي تحتاج إلى تثبيت.",text:"عندما تسجل دخولك، نحتفظ بالأسئلة التي أخطأت فيها لتراجعها لاحقًا.",href:"/login",action:"افتح بنك أخطائك"},history:{eyebrow:"سجل التعلم",title:"سجل الاختبارات",description:"شاهد كل الجولات التي أنجزتها ونتائجك السابقة.",text:"سجّل دخولك حتى يبقى تقدمك معك في كل مرة.",href:"/login",action:"تسجيل الدخول"},classes:{eyebrow:"تعلم جماعي",title:"فصولي",description:"أنشئ فصلًا أو انضم إلى مجموعة تعلم.",text:"ابدأ بإنشاء فصل خاص بك أو استخدم كود الدعوة للانضمام إلى زملائك.",href:"/login",action:"تسجيل الدخول"},community:{eyebrow:"مساحة الطلاب",title:"المجتمع",description:"اسأل، شارك، وتعلّم مع طلاب آخرين.",text:"تحتاج إلى تسجيل الدخول حتى تكتب رسالة في المجتمع.",href:"/login",action:"اكتب أول رسالة"}}; const d=data[kind]; return <><PageTitle eyebrow={d.eyebrow} title={d.title} description={d.description} /><section className="panel large-empty"><Empty title={d.text} text="ستجد هنا تجربة منظمة ومتصلة ببقية أدوات المنصة." href={d.href} action={d.action} /></section></>; }
function Login() { return <><div className="auth-page"><div className="auth-brand"><Brand /></div><div className="auth-card"><span className="eyebrow">مساحتك التعليمية</span><h1>سجّل دخولك وواصل التقدم.</h1><p>احفظ نتائجك، تابع أخطاءك، وارجع إلى اختباراتك من أي جهاز.</p><label>البريد الإلكتروني<input type="email" placeholder="you@example.com" /></label><label>كلمة المرور<input type="password" placeholder="••••••••" /></label><Button>دخول <ArrowLeft size={16} /></Button><p className="auth-foot">ليس لديك حساب؟ <Link href="/register">أنشئ حسابًا جديدًا</Link></p></div></div></>; }
function Register() { return <><div className="auth-page"><div className="auth-brand"><Brand /></div><div className="auth-card"><span className="eyebrow">ابدأ من هنا</span><h1>أنشئ حسابك الدراسي.</h1><p>مكان واحد لتدريبك، اختباراتك، وتقدمك.</p><label>الاسم الكامل<input placeholder="اكتب اسمك بالكامل" /></label><label>البريد الإلكتروني<input type="email" placeholder="you@example.com" /></label><label>كلمة المرور<input type="password" placeholder="8 أحرف على الأقل" /></label><Button>إنشاء الحساب <ArrowLeft size={16} /></Button><p className="auth-foot">لديك حساب؟ <Link href="/login">سجّل الدخول</Link></p></div></div></>; }
function App() { return <Switch><Route path="/login" component={Login} /><Route path="/register" component={Register} /><Route><Shell><Switch><Route path="/" component={Dashboard} /><Route path="/quiz-create" component={QuizCreate} /><Route path="/practice" component={Practice} /><Route path="/daily" component={Daily} /><Route path="/leaderboard" component={Leaderboard} /><Route path="/my-quizzes"><SimplePage kind="my-quizzes" /></Route><Route path="/mistakes"><SimplePage kind="mistakes" /></Route><Route path="/history"><SimplePage kind="history" /></Route><Route path="/classes"><SimplePage kind="classes" /></Route><Route path="/community"><SimplePage kind="community" /></Route><Route><Dashboard /></Route></Switch></Shell></Route></Switch>; }
export default App;
